// auto generated by go tool dist

package sys

const DefaultGoroot = `/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot`
const TheVersion = `go1.6.1 (appengine-1.9.38)`
const Goexperiment = ``
const StackGuardMultiplier = 1

